---
title: "Untitled"
format: pdf
editor: visual
---

```{r}
#| label: load
#| cache: false
# Load all required packages
library(tidyverse)
library(dplyr)
library(ggplot2)
library(fabletools)
library(patchwork)
library(knitr)
library(kableExtra)
library(latex2exp)

source("../R/nemenyi.R") # MCB test
source("../R/analysis.R") # Other functions used for analysis

theme_set(theme_get() + theme(text = element_text(family = "Source Sans Pro")))
```

## Labour

```{r}
#| label: tbl-labour-rmse_3
#| echo: false
#| message: false
#| warning: false
#| results: asis
#| tbl-cap: 3 test sets.

rmse_labour_3 <- readRDS("results/labour_rmse.rds")
latex_table(rmse_labour_3)
```

```{r}
#| label: tbl-labour-rmse_4
#| echo: false
#| message: false
#| warning: false
#| results: asis
#| tbl-cap: 4 test sets.

rmse_labour_4 <- readRDS("results/labour_rmse_4.rds")
latex_table(rmse_labour_4)
```

```{r}
#| label: tbl-labour-rmse_5
#| echo: false
#| message: false
#| warning: false
#| results: asis
#| tbl-cap: 5 test sets.

rmse_labour_5 <- readRDS("results/labour_rmse_5.rds")
latex_table(rmse_labour_5)
```

## Tourism

```{r}
#| label: tbl-tourism-rmse_3
#| echo: false
#| message: false
#| warning: false
#| results: asis
#| tbl-cap: 3 test sets.

rmse_tourism_3 <- readRDS("results/tourism_rmse.rds")
latex_table(rmse_tourism_3)
```

```{r}
#| label: tbl-tourism-rmse_4
#| echo: false
#| message: false
#| warning: false
#| results: asis
#| tbl-cap: 4 test sets.

rmse_tourism_4 <- readRDS("results/tourism_rmse_4.rds")
latex_table(rmse_tourism_4)
```

```{r}
#| label: tbl-tourism-rmse_5
#| echo: false
#| message: false
#| warning: false
#| results: asis
#| tbl-cap: 5 test sets.

rmse_tourism_5 <- readRDS("results/tourism_rmse_5.rds")
latex_table(rmse_tourism_5)
```
